name: router ci

on: [push, workflow_dispatch]

jobs:
  test:
    name: test nix flake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github=${{ github.token }}

      - name: configure cachix
        uses: cachix/cachix-action@v10
        with:
          name: justinrubek
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: run checks
        run: nix flake check
